name: faces-PyJs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'

      # Step 3: Print Python version and pip version
      - name: Print Python version
        run: |
          python --version
          pip --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Build distribution files
      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel

      # Step 6: Install twine
      - name: Install twine
        run: |
          python -m pip install --upgrade twine

      # Step 7: Upload to Test PyPI
      - name: Upload
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.API_KEY }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*